# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Empresas iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AFNetworking", :git => "https://github.com/jpmfagundes/AFNetworking.git", :commit => "64741e8d341de802093371b6d8f805fe62d60cc5"
  # Pods for Empresas iOS

  target 'Empresas iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
